version: "3"
services:
  scheduler:
    build:
      context: .
      dockerfile: scheduler-dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"

  coordinator:
    build:
      context: .
      dockerfile: coordinator-dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: worker-dockerfile
    environment:
      WORKER_ADDRESS: worker
    env_file:
      - .env
    depends_on:
      - coordinator
