{{- $root := . -}}
{{- range $appName, $appValues := .Values.apps }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "taskmanager.fullname" $root }}-{{ $appName }}-clusterrole
  labels:
    app: {{ include "taskmanager.fullname" $root }}-{{ $appName }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taskmanager.fullname" $root }}-{{ $appName }}-sa
  namespace: {{ $appValues.namespace }}
  labels:
    app: {{ include "taskmanager.fullname" $root }}-{{ $appName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "taskmanager.fullname" $root }}-{{ $appName }}-clusterrolebinding
  labels:
    app: {{ include "taskmanager.fullname" $root }}-{{ $appName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "taskmanager.fullname" $root }}-{{ $appName }}-sa
    namespace: {{ $appValues.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "taskmanager.fullname" $root }}-{{ $appName }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}
