{{- $root := . -}}
{{- range $appName, $appValues := .Values.apps }}
{{- if $appValues.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" (list $appName $root) }}
  namespace: {{ $appValues.namespace | default "default" }}
  labels:
    app: {{ include "taskmanager.fullname" (list $appName $root) }}
spec:
  type: {{ $appValues.service.type }}
  ports:
    - port: {{ $appValues.service.port }}
      targetPort: {{ $appValues.service.port }}
  selector:
    app: {{ include "taskmanager.fullname" (list $appName $root) }}
    {{- end }}
---
{{- end }}
