name: taskmanager
nameOverride: ""
fullname: taskmanager
fullnameOverride: ""
apps:
  coordinator:
    replicaCount: 1
    namespace: default
    image:
      repository: coordinator
      pullPolicy: IfNotPresent
      tag: "latest"
      args: ["--coordinator_port=:8080"]

    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: {}
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: coordinator.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi

  scheduler:
    replicaCount: 1
    namespace: default
    image:
      repository: scheduler
      pullPolicy: IfNotPresent
      tag: "latest"
      args: ["--scheduler_port=:8081"]

    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: {}
    service:
      type: ClusterIP
      port: 8081
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi

  worker:
    replicaCount: 1
    namespace: default
    image:
      repository: worker
      pullPolicy: IfNotPresent
      tag: "latest"
      args: ["--coordinator=taskmanager-coordinator:8080"]

    nameOverride: ""
    fullnameOverride: ""
    podAnnotations: {}
    service:
      type: ClusterIP
      port: 8082
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
